[web] Switch transferFromImageBitmap to be invoked using js.callMethod
The current implementation of captureFrame works in debug mode but fails in
profile and release mode with `TypeError: ... is not a function`. This commit
uses js.callMethod to invoke the method instead of using the native api, which
seems to resolve this issue.

Fixes #621